### ISSUE TITLE
Adding extra step for crash reporting

### ISSUE THREAD

**Issue by flexbox** [atolye15/crna-recipe#2]
I think we can add an extra step

### Step 14: track your fist bug

Create an account on {sentry}(https://sentry.io/signup/)
```
yarn add react-native-sentry
react-native link react-native-sentry
```
Add and some configuration.

@hsnaydd 
Let me know if you want a PR for this.

**Comment by hsnaydd** [comment]
Hi @flexbox;

First of all, thank you for your suggestion. We aim to keep this recipe simple, I think your suggestion is a bit advanced. Considering that people who use this recipe are beginners, adding this additional step would be confusing.

**Comment by flexbox** [comment]
Agreed we can always add "just this simple extra step" 😉

**Comment by EricMcRay** [comment]
I agree with @hsnaydd. This type of packages is variable, I prefer Crashliytics for example. We aim to provide some layout, configuration with this recipe to save some time and bootstrapping mess from the beginning.

For example; If you have some stuff you do every time you start a new react-native project, please share with us.
