### ISSUE TITLE
ESLint instead of TSLint

### ISSUE THREAD

**Issue by EricMcRay** [atolye15/crna-recipe#3]
Looks like TSLint moving self under to ESLint as a plugin. We can replace TSLint with ESLint.

We can take reference from [cra-recipe](https://github.com/atolye15/cra-recipe/pull/3#pullrequestreview-228261155). 

For eslint changes here is the PR for cra-recipe: https://github.com/atolye15/cra-recipe/pull/3#pullrequestreview-228261155

**Comment by flexbox** [comment]
Just wanted to create the same issue after [reading this article](https://medium.com/palantir/tslint-in-2019-1a144c2317a9)

> In order to avoid bifurcating the linting tool space for TypeScript, we therefore plan to deprecate TSLint and focus our efforts instead on improving ESLint’s TypeScript support.
