### ISSUE TITLE
Storybook browser addons not showing

### ISSUE THREAD

**Issue by inf3cti0n95** [atolye15/crna-recipe#4]
Storybook browser addons not showing up. And none of the components are being listed in storybook on browser

**Comment by hsnaydd** [comment]
Hi @inf3cti0n95;

I don't fully understand your problem, can you give me some more details?
We are not installing any add-on except mandatory add-ons. Already many add-ons do not work for react-native.

**Comment by inf3cti0n95** [comment]
Actually, I solved it, the issue is that you are specifying in readme to change file extensions of files in storybook directory to .ts from .js. But addons.ts is not detected by storybook
